# Generated by Django 3.1 on 2020-08-07 20:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 20, 27, 44, 538388, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='rss',
            name='description',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='rss',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rss',
            name='title',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='rss',
            name='url',
            field=models.URLField(),
        ),
    ]
