# Generated by Django 3.1 on 2020-08-12 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20200807_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 2, 11, 51, 495097, tzinfo=utc)),
        ),
    ]
