# Generated by Django 3.1 on 2020-08-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20200812_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='date',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
